# How to "balance services" with multiple container
# https://stackoverflow.com/questions/47838031/several-replicas-into-docker-swarm

version: "3.9"

services:
  web:
    image: kaenova/ci-cd-playground:latest
    ports:
      - "2010:2000"
    networks:
      - web-net
    deploy:
      replicas: 4

networks:
  web-net:
    driver: overlay
