name: Staging Docker Imaging - Backend

on:
  push:
    branches:
      - "main"

env:
  TAGS: ${{ github.sha }}
  
  # Please fill this
  DOCKER_REPOSITORY: kaenova/ci-cd-playground

jobs: 
  DockerImagingService:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build --tag "$DOCKER_REPOSITORY:$TAGS" --tag "$DOCKER_REPOSITORY:latest" .

      - name: DockerHub Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Dockerhub Push
        run: docker push $DOCKER_REPOSITORY --all-tags